# Generated by Django 5.2.7 on 2025-11-09 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('hire_date', models.DateField()),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.RemoveField(
            model_name='passengerprofile',
            name='passport_number',
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='nationality',
            field=models.CharField(default='000', max_length=50),
        ),
        migrations.AddField(
            model_name='passengerprofile',
            name='passport',
            field=models.CharField(default='000', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='phone_number',
            field=models.CharField(default='000', max_length=20),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='passengerprofile',
            table='PassengerProfile',
        ),
    ]
