# Generated by Django 5.2.7 on 2025-11-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admin_remove_passengerprofile_passport_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='hire_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='passport',
            field=models.CharField(max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='passengerprofile',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
