# Generated by Django 5.2.7 on 2025-11-17 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('aircraft_id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('economy_class', models.PositiveIntegerField(default=150)),
                ('business_class', models.PositiveIntegerField(default=16)),
                ('first_class', models.PositiveIntegerField(default=8)),
            ],
            options={
                'db_table': 'Aircraft',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('airport_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Airport',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('economy_price', models.DecimalField(decimal_places=2, default=300.0, max_digits=10)),
                ('business_price', models.DecimalField(decimal_places=2, default=800.0, max_digits=10)),
                ('first_class_price', models.DecimalField(decimal_places=2, default=1500.0, max_digits=10)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flights.aircraft')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arriving_flights', to='flights.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departing_flights', to='flights.airport')),
            ],
            options={
                'db_table': 'Flight',
            },
        ),
    ]
