# Generated by Django 5.2.7 on 2025-11-17 18:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('number_of_passengers', models.PositiveIntegerField(default=1)),
                ('seat_class', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], default='Economy', max_length=20)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flights.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='users.passengerprofile')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+[A-Za-z]+$', 'Invalid seat number format')])),
                ('passenger_name', models.CharField(max_length=100)),
                ('passport', models.CharField(max_length=20, unique=True)),
                ('passenger_dob', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.booking')),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
    ]
