# Generated by Django 5.2.7 on 2025-11-10 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d+[A-Za-z]+$', 'Invalid seat number format')])),
                ('passenger_name', models.CharField(max_length=100)),
                ('passport', models.CharField(max_length=20, unique=True)),
                ('passenger_dob', models.DateField()),
                ('nationality', models.CharField(max_length=50)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.booking')),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
    ]
